// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7MH9WXVOXByaevemnr_xHdqDJDdjoYx4',
    appId: '1:268712968367:web:83319559fd522c6795145a',
    messagingSenderId: '268712968367',
    projectId: 'schoolvt-64be7',
    authDomain: 'schoolvt-64be7.firebaseapp.com',
    storageBucket: 'schoolvt-64be7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKsJvbRCryKKYmP92_h1cvooV2_Hq-v7U',
    appId: '1:268712968367:android:b87bb8eed5a4b86595145a',
    messagingSenderId: '268712968367',
    projectId: 'schoolvt-64be7',
    storageBucket: 'schoolvt-64be7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5m3CHnDB6eaZbQvZ_q5PUfFYiFJ7VVt4',
    appId: '1:268712968367:ios:7380a15fdf781a6a95145a',
    messagingSenderId: '268712968367',
    projectId: 'schoolvt-64be7',
    storageBucket: 'schoolvt-64be7.appspot.com',
    iosBundleId: 'com.schoolvtacademic.vtschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5m3CHnDB6eaZbQvZ_q5PUfFYiFJ7VVt4',
    appId: '1:268712968367:ios:3e6ae86cbf9072fa95145a',
    messagingSenderId: '268712968367',
    projectId: 'schoolvt-64be7',
    storageBucket: 'schoolvt-64be7.appspot.com',
    iosBundleId: 'com.schoolvtacademic.vtschool.RunnerTests',
  );
}
